[package]
name = "checks-please"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
axum = "0.7.6"
minijinja = {version="2.3.1", features=["loader"]}
tokio = {version="1.40.0", features=["full"]}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
